[2024-06-03 17:19:04,685] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/wangzc/database/flask_database/demo/blueprint/hppied.py", line 19, in index
    return render_template('home/home.html')
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/jinja2/environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/wangzc/database/flask_database/demo/templates/home/home.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/wangzc/database/flask_database/demo/templates/base.html", line 33, in top-level template code
    {% block content %}
  File "/home/wangzc/database/flask_database/demo/templates/home/home.html", line 57, in block 'content'
    <a href="{{ url_for('search') }}">
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/flask/app.py", line 1084, in url_for
    return self.handle_url_build_error(error, endpoint, values)
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/flask/app.py", line 1073, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/werkzeug/routing/map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'search'. Did you mean 'search.index' instead?
[2024-06-03 17:19:34 +0800] [571189] [CRITICAL] WORKER TIMEOUT (pid:571194)
[2024-06-03 17:19:34 +0800] [571194] [ERROR] Error handling request (no URI read)
Traceback (most recent call last):
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/gunicorn/workers/sync.py", line 134, in handle
    req = next(parser)
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/gunicorn/http/parser.py", line 42, in __next__
    self.mesg = self.mesg_class(self.cfg, self.unreader, self.source_addr, self.req_count)
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/gunicorn/http/message.py", line 257, in __init__
    super().__init__(cfg, unreader, peer_addr)
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/gunicorn/http/message.py", line 60, in __init__
    unused = self.parse(self.unreader)
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/gunicorn/http/message.py", line 269, in parse
    self.get_data(unreader, buf, stop=True)
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/gunicorn/http/message.py", line 260, in get_data
    data = unreader.read()
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/gunicorn/http/unreader.py", line 37, in read
    d = self.chunk()
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/gunicorn/http/unreader.py", line 64, in chunk
    return self.sock.recv(self.mxchunk)
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/gunicorn/workers/base.py", line 203, in handle_abort
    sys.exit(1)
SystemExit: 1
[2024-06-03 17:21:40 +0800] [571836] [CRITICAL] WORKER TIMEOUT (pid:571968)
[2024-06-03 17:21:40 +0800] [571968] [ERROR] Error handling request (no URI read)
Traceback (most recent call last):
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/gunicorn/workers/sync.py", line 134, in handle
    req = next(parser)
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/gunicorn/http/parser.py", line 42, in __next__
    self.mesg = self.mesg_class(self.cfg, self.unreader, self.source_addr, self.req_count)
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/gunicorn/http/message.py", line 257, in __init__
    super().__init__(cfg, unreader, peer_addr)
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/gunicorn/http/message.py", line 60, in __init__
    unused = self.parse(self.unreader)
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/gunicorn/http/message.py", line 269, in parse
    self.get_data(unreader, buf, stop=True)
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/gunicorn/http/message.py", line 260, in get_data
    data = unreader.read()
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/gunicorn/http/unreader.py", line 37, in read
    d = self.chunk()
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/gunicorn/http/unreader.py", line 64, in chunk
    return self.sock.recv(self.mxchunk)
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/gunicorn/workers/base.py", line 203, in handle_abort
    sys.exit(1)
SystemExit: 1
[2024-06-03 17:24:13 +0800] [573457] [CRITICAL] WORKER TIMEOUT (pid:573460)
[2024-06-03 17:24:13 +0800] [573460] [ERROR] Error handling request (no URI read)
Traceback (most recent call last):
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/gunicorn/workers/sync.py", line 134, in handle
    req = next(parser)
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/gunicorn/http/parser.py", line 42, in __next__
    self.mesg = self.mesg_class(self.cfg, self.unreader, self.source_addr, self.req_count)
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/gunicorn/http/message.py", line 257, in __init__
    super().__init__(cfg, unreader, peer_addr)
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/gunicorn/http/message.py", line 60, in __init__
    unused = self.parse(self.unreader)
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/gunicorn/http/message.py", line 269, in parse
    self.get_data(unreader, buf, stop=True)
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/gunicorn/http/message.py", line 260, in get_data
    data = unreader.read()
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/gunicorn/http/unreader.py", line 37, in read
    d = self.chunk()
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/gunicorn/http/unreader.py", line 64, in chunk
    return self.sock.recv(self.mxchunk)
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/gunicorn/workers/base.py", line 203, in handle_abort
    sys.exit(1)
SystemExit: 1
[2024-06-03 20:10:33 +0800] [585710] [CRITICAL] WORKER TIMEOUT (pid:585841)
[2024-06-03 20:10:33 +0800] [585841] [ERROR] Error handling request (no URI read)
Traceback (most recent call last):
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/gunicorn/workers/sync.py", line 134, in handle
    req = next(parser)
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/gunicorn/http/parser.py", line 42, in __next__
    self.mesg = self.mesg_class(self.cfg, self.unreader, self.source_addr, self.req_count)
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/gunicorn/http/message.py", line 257, in __init__
    super().__init__(cfg, unreader, peer_addr)
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/gunicorn/http/message.py", line 60, in __init__
    unused = self.parse(self.unreader)
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/gunicorn/http/message.py", line 269, in parse
    self.get_data(unreader, buf, stop=True)
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/gunicorn/http/message.py", line 260, in get_data
    data = unreader.read()
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/gunicorn/http/unreader.py", line 37, in read
    d = self.chunk()
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/gunicorn/http/unreader.py", line 64, in chunk
    return self.sock.recv(self.mxchunk)
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/gunicorn/workers/base.py", line 203, in handle_abort
    sys.exit(1)
SystemExit: 1
[2024-06-03 20:11:54 +0800] [586292] [CRITICAL] WORKER TIMEOUT (pid:586359)
[2024-06-03 20:11:54 +0800] [586359] [ERROR] Error handling request (no URI read)
Traceback (most recent call last):
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/gunicorn/workers/sync.py", line 134, in handle
    req = next(parser)
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/gunicorn/http/parser.py", line 42, in __next__
    self.mesg = self.mesg_class(self.cfg, self.unreader, self.source_addr, self.req_count)
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/gunicorn/http/message.py", line 257, in __init__
    super().__init__(cfg, unreader, peer_addr)
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/gunicorn/http/message.py", line 60, in __init__
    unused = self.parse(self.unreader)
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/gunicorn/http/message.py", line 269, in parse
    self.get_data(unreader, buf, stop=True)
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/gunicorn/http/message.py", line 260, in get_data
    data = unreader.read()
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/gunicorn/http/unreader.py", line 37, in read
    d = self.chunk()
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/gunicorn/http/unreader.py", line 64, in chunk
    return self.sock.recv(self.mxchunk)
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/gunicorn/workers/base.py", line 203, in handle_abort
    sys.exit(1)
SystemExit: 1
[2024-06-03 20:54:46,790] ERROR in app: Exception on /fetch-data [POST]
Traceback (most recent call last):
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/wangzc/database/flask_database/demo/blueprint/search.py", line 39, in fetch_data
    with open(about_path) as file:
FileNotFoundError: [Errno 2] No such file or directory: 'demo/static/images/A2M-AS1_about.txt'
[2024-06-03 21:22:57,373] ERROR in app: Exception on /about [GET]
Traceback (most recent call last):
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/wangzc/database/flask_database/demo/blueprint/about.py", line 19, in index
    return render_template('about/about.html')
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/flask/templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/jinja2/environment.py", line 1084, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/jinja2/environment.py", line 1013, in get_template
    return self._load_template(name, globals)
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/jinja2/environment.py", line 972, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/jinja2/loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/jinja2/environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/jinja2/environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/wangzc/database/flask_database/demo/templates/about/about.html", line 143, in template
    {% endblock content %}
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'endblock'.
[2024-06-03 21:23:27 +0800] [605636] [CRITICAL] WORKER TIMEOUT (pid:605638)
[2024-06-03 21:23:27 +0800] [605638] [ERROR] Error handling request (no URI read)
Traceback (most recent call last):
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/gunicorn/workers/sync.py", line 134, in handle
    req = next(parser)
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/gunicorn/http/parser.py", line 42, in __next__
    self.mesg = self.mesg_class(self.cfg, self.unreader, self.source_addr, self.req_count)
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/gunicorn/http/message.py", line 257, in __init__
    super().__init__(cfg, unreader, peer_addr)
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/gunicorn/http/message.py", line 60, in __init__
    unused = self.parse(self.unreader)
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/gunicorn/http/message.py", line 269, in parse
    self.get_data(unreader, buf, stop=True)
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/gunicorn/http/message.py", line 260, in get_data
    data = unreader.read()
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/gunicorn/http/unreader.py", line 37, in read
    d = self.chunk()
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/gunicorn/http/unreader.py", line 64, in chunk
    return self.sock.recv(self.mxchunk)
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/gunicorn/workers/base.py", line 203, in handle_abort
    sys.exit(1)
SystemExit: 1
[2024-06-03 21:24:41,051] ERROR in app: Exception on /about [GET]
Traceback (most recent call last):
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/wangzc/database/flask_database/demo/blueprint/about.py", line 19, in index
    return render_template('about/about.html')
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/flask/templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/jinja2/environment.py", line 1084, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/jinja2/environment.py", line 1013, in get_template
    return self._load_template(name, globals)
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/jinja2/environment.py", line 972, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/jinja2/loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/jinja2/environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/jinja2/environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/wangzc/database/flask_database/demo/templates/about/about.html", line 143, in template
    {% endblock content %}
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'endblock'.
[2024-06-03 21:25:11 +0800] [605636] [CRITICAL] WORKER TIMEOUT (pid:605703)
[2024-06-03 21:25:11 +0800] [605703] [ERROR] Error handling request (no URI read)
Traceback (most recent call last):
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/gunicorn/workers/sync.py", line 134, in handle
    req = next(parser)
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/gunicorn/http/parser.py", line 42, in __next__
    self.mesg = self.mesg_class(self.cfg, self.unreader, self.source_addr, self.req_count)
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/gunicorn/http/message.py", line 257, in __init__
    super().__init__(cfg, unreader, peer_addr)
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/gunicorn/http/message.py", line 60, in __init__
    unused = self.parse(self.unreader)
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/gunicorn/http/message.py", line 269, in parse
    self.get_data(unreader, buf, stop=True)
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/gunicorn/http/message.py", line 260, in get_data
    data = unreader.read()
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/gunicorn/http/unreader.py", line 37, in read
    d = self.chunk()
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/gunicorn/http/unreader.py", line 64, in chunk
    return self.sock.recv(self.mxchunk)
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/gunicorn/workers/base.py", line 203, in handle_abort
    sys.exit(1)
SystemExit: 1
[2024-06-03 21:25:56 +0800] [606305] [CRITICAL] WORKER TIMEOUT (pid:606436)
[2024-06-03 21:25:56 +0800] [606305] [CRITICAL] WORKER TIMEOUT (pid:606547)
[2024-06-03 21:25:56 +0800] [606436] [ERROR] Error handling request (no URI read)
Traceback (most recent call last):
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/gunicorn/workers/sync.py", line 134, in handle
    req = next(parser)
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/gunicorn/http/parser.py", line 42, in __next__
    self.mesg = self.mesg_class(self.cfg, self.unreader, self.source_addr, self.req_count)
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/gunicorn/http/message.py", line 257, in __init__
    super().__init__(cfg, unreader, peer_addr)
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/gunicorn/http/message.py", line 60, in __init__
    unused = self.parse(self.unreader)
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/gunicorn/http/message.py", line 269, in parse
    self.get_data(unreader, buf, stop=True)
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/gunicorn/http/message.py", line 260, in get_data
    data = unreader.read()
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/gunicorn/http/unreader.py", line 37, in read
    d = self.chunk()
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/gunicorn/http/unreader.py", line 64, in chunk
    return self.sock.recv(self.mxchunk)
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/gunicorn/workers/base.py", line 203, in handle_abort
    sys.exit(1)
SystemExit: 1
[2024-06-03 21:25:56 +0800] [606547] [ERROR] Error handling request (no URI read)
Traceback (most recent call last):
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/gunicorn/workers/sync.py", line 134, in handle
    req = next(parser)
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/gunicorn/http/parser.py", line 42, in __next__
    self.mesg = self.mesg_class(self.cfg, self.unreader, self.source_addr, self.req_count)
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/gunicorn/http/message.py", line 257, in __init__
    super().__init__(cfg, unreader, peer_addr)
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/gunicorn/http/message.py", line 60, in __init__
    unused = self.parse(self.unreader)
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/gunicorn/http/message.py", line 269, in parse
    self.get_data(unreader, buf, stop=True)
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/gunicorn/http/message.py", line 260, in get_data
    data = unreader.read()
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/gunicorn/http/unreader.py", line 37, in read
    d = self.chunk()
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/gunicorn/http/unreader.py", line 64, in chunk
    return self.sock.recv(self.mxchunk)
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/gunicorn/workers/base.py", line 203, in handle_abort
    sys.exit(1)
SystemExit: 1
[2024-06-04 14:40:56 +0800] [624378] [CRITICAL] WORKER TIMEOUT (pid:624379)
[2024-06-04 14:40:56 +0800] [624379] [ERROR] Error handling request (no URI read)
Traceback (most recent call last):
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/gunicorn/workers/sync.py", line 134, in handle
    req = next(parser)
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/gunicorn/http/parser.py", line 42, in __next__
    self.mesg = self.mesg_class(self.cfg, self.unreader, self.source_addr, self.req_count)
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/gunicorn/http/message.py", line 257, in __init__
    super().__init__(cfg, unreader, peer_addr)
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/gunicorn/http/message.py", line 60, in __init__
    unused = self.parse(self.unreader)
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/gunicorn/http/message.py", line 269, in parse
    self.get_data(unreader, buf, stop=True)
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/gunicorn/http/message.py", line 260, in get_data
    data = unreader.read()
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/gunicorn/http/unreader.py", line 37, in read
    d = self.chunk()
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/gunicorn/http/unreader.py", line 64, in chunk
    return self.sock.recv(self.mxchunk)
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/gunicorn/workers/base.py", line 203, in handle_abort
    sys.exit(1)
SystemExit: 1
[2024-06-04 14:49:47 +0800] [624378] [CRITICAL] WORKER TIMEOUT (pid:624509)
[2024-06-04 14:49:47 +0800] [624509] [ERROR] Error handling request (no URI read)
Traceback (most recent call last):
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/gunicorn/workers/sync.py", line 134, in handle
    req = next(parser)
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/gunicorn/http/parser.py", line 42, in __next__
    self.mesg = self.mesg_class(self.cfg, self.unreader, self.source_addr, self.req_count)
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/gunicorn/http/message.py", line 257, in __init__
    super().__init__(cfg, unreader, peer_addr)
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/gunicorn/http/message.py", line 60, in __init__
    unused = self.parse(self.unreader)
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/gunicorn/http/message.py", line 269, in parse
    self.get_data(unreader, buf, stop=True)
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/gunicorn/http/message.py", line 260, in get_data
    data = unreader.read()
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/gunicorn/http/unreader.py", line 37, in read
    d = self.chunk()
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/gunicorn/http/unreader.py", line 64, in chunk
    return self.sock.recv(self.mxchunk)
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/gunicorn/workers/base.py", line 203, in handle_abort
    sys.exit(1)
SystemExit: 1
[2024-06-04 14:52:55 +0800] [624378] [CRITICAL] WORKER TIMEOUT (pid:627312)
[2024-06-04 14:52:55 +0800] [627312] [ERROR] Error handling request (no URI read)
Traceback (most recent call last):
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/gunicorn/workers/sync.py", line 134, in handle
    req = next(parser)
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/gunicorn/http/parser.py", line 42, in __next__
    self.mesg = self.mesg_class(self.cfg, self.unreader, self.source_addr, self.req_count)
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/gunicorn/http/message.py", line 257, in __init__
    super().__init__(cfg, unreader, peer_addr)
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/gunicorn/http/message.py", line 60, in __init__
    unused = self.parse(self.unreader)
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/gunicorn/http/message.py", line 269, in parse
    self.get_data(unreader, buf, stop=True)
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/gunicorn/http/message.py", line 260, in get_data
    data = unreader.read()
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/gunicorn/http/unreader.py", line 37, in read
    d = self.chunk()
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/gunicorn/http/unreader.py", line 64, in chunk
    return self.sock.recv(self.mxchunk)
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/gunicorn/workers/base.py", line 203, in handle_abort
    sys.exit(1)
SystemExit: 1
[2024-06-04 14:54:31 +0800] [624510] [ERROR] Error handling request (no URI read)
Traceback (most recent call last):
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/gunicorn/workers/sync.py", line 134, in handle
    req = next(parser)
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/gunicorn/http/parser.py", line 42, in __next__
    self.mesg = self.mesg_class(self.cfg, self.unreader, self.source_addr, self.req_count)
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/gunicorn/http/message.py", line 257, in __init__
    super().__init__(cfg, unreader, peer_addr)
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/gunicorn/http/message.py", line 60, in __init__
    unused = self.parse(self.unreader)
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/gunicorn/http/message.py", line 269, in parse
    self.get_data(unreader, buf, stop=True)
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/gunicorn/http/message.py", line 260, in get_data
    data = unreader.read()
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/gunicorn/http/unreader.py", line 37, in read
    d = self.chunk()
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/gunicorn/http/unreader.py", line 64, in chunk
    return self.sock.recv(self.mxchunk)
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/gunicorn/workers/base.py", line 197, in handle_quit
    time.sleep(0.1)
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/gunicorn/workers/base.py", line 198, in handle_quit
    sys.exit(0)
SystemExit: 0
[2024-06-04 15:37:04 +0800] [632640] [CRITICAL] WORKER TIMEOUT (pid:632708)
[2024-06-04 15:37:04 +0800] [632708] [ERROR] Error handling request (no URI read)
Traceback (most recent call last):
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/gunicorn/workers/sync.py", line 134, in handle
    req = next(parser)
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/gunicorn/http/parser.py", line 42, in __next__
    self.mesg = self.mesg_class(self.cfg, self.unreader, self.source_addr, self.req_count)
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/gunicorn/http/message.py", line 257, in __init__
    super().__init__(cfg, unreader, peer_addr)
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/gunicorn/http/message.py", line 60, in __init__
    unused = self.parse(self.unreader)
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/gunicorn/http/message.py", line 269, in parse
    self.get_data(unreader, buf, stop=True)
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/gunicorn/http/message.py", line 260, in get_data
    data = unreader.read()
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/gunicorn/http/unreader.py", line 37, in read
    d = self.chunk()
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/gunicorn/http/unreader.py", line 64, in chunk
    return self.sock.recv(self.mxchunk)
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/gunicorn/workers/base.py", line 203, in handle_abort
    sys.exit(1)
SystemExit: 1
[2024-06-04 15:56:10,097] ERROR in app: Exception on /fetch-data [POST]
Traceback (most recent call last):
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/wangzc/anaconda3/envs/flask2024/lib/python3.9/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/wangzc/database/flask_database/demo/blueprint/search.py", line 39, in fetch_data
    with open(about_path) as file:
FileNotFoundError: [Errno 2] No such file or directory: 'demo/static/images/A2ML1-AS1_about.txt'
[2024-06-05 14:42:18 +0800] [632640] [ERROR] Worker (pid:632707) was sent SIGHUP!
[2024-06-05 14:42:18 +0800] [632640] [ERROR] Worker (pid:632773) was sent SIGHUP!
[2024-06-05 14:42:18 +0800] [632640] [ERROR] Worker (pid:632772) was sent SIGHUP!
[2024-06-05 14:42:18 +0800] [632640] [ERROR] Worker (pid:632642) was sent SIGHUP!
[2024-06-05 14:42:18 +0800] [632640] [ERROR] Worker (pid:632643) was sent SIGHUP!
[2024-06-05 14:42:18 +0800] [632640] [ERROR] Worker (pid:632641) was sent SIGHUP!
[2024-06-05 14:42:19 +0800] [632640] [ERROR] Worker (pid:637695) was sent SIGTERM!
[2024-06-05 14:42:19 +0800] [632640] [ERROR] Worker (pid:637698) was sent SIGTERM!
[2024-06-05 14:42:19 +0800] [632640] [ERROR] Worker (pid:637692) was sent SIGTERM!
[2024-06-05 14:42:19 +0800] [632640] [ERROR] Worker (pid:637694) was sent SIGTERM!
[2024-06-05 14:42:19 +0800] [632640] [ERROR] Worker (pid:637696) was sent SIGTERM!
[2024-06-05 14:42:19 +0800] [632640] [ERROR] Worker (pid:637691) was sent SIGTERM!
[2024-06-05 14:42:19 +0800] [632640] [ERROR] Worker (pid:637693) was sent SIGTERM!
[2024-06-05 14:42:19 +0800] [632640] [ERROR] Worker (pid:637697) was sent SIGTERM!
